# Generated by Django 4.2.1 on 2023-05-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='text',
            field=models.TextField(default=None, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advert',
            name='text',
            field=models.TextField(verbose_name='Текст объявления'),
        ),
    ]
