# Generated by Django 4.2.1 on 2023-05-18 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_reply_text_alter_advert_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='accepted_reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_reply', to='mysite.reply', verbose_name='Принятый отклик'),
        ),
    ]
